version: '3.8'
services:

  formkiq:
    image: formkiq/api-server:1.13.0-SNAPSHOT
    depends_on:
      - minio
      - dynamodb
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DYNAMODB_URL: http://dynamodb:8000
      S3_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
  minio:
    image: minio/minio:RELEASE.2023-08-23T10-07-06Z
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_DOMAIN: minio
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      # MINIO_AUDIT_WEBHOOK_ENABLE_DOCUMENTS: on
      # MINIO_AUDIT_WEBHOOK_ENDPOINT_DOCUMENTS: http://formkiq:8080/minio/audit
      MINIO_NOTIFY_WEBHOOK_ENABLE_DOCUMENTS: on
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_DOCUMENTS: http://formkiq:8080/minio/s3/documents
      MINIO_NOTIFY_WEBHOOK_ENABLE_STAGINGDOCUMENTS: on
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_STAGINGDOCUMENTS: http://formkiq:8080/minio/s3/stagingdocuments
    networks:
      default:
        aliases:
          - documents.minio
          - stagingdocuments.minio
    volumes:
      - ./formkiq/minio:/data
    command: server /data --console-address :9090

  dynamodb:
    image: amazon/dynamodb-local:1.22.0
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    ports:
      - "8000:8000"
    volumes:
      - ./formkiq/dynamodb:/data