version: '3.8'
services:

  formkiq:
    image: formkiq/netty-server:1.13.0
    depends_on:
      - minio
      - dynamodb
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DYNAMODB_URL: http://dynamodb:8000
      S3_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

  minio:
    image: minio/minio:RELEASE.2023-08-23T10-07-06Z
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_NOTIFY_WEBHOOK_ENABLE_DOCUMENTS: on
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_DOCUMENTS: http://localhost:8080/minio/s3/documents
      MINIO_NOTIFY_WEBHOOK_ENABLE_STAGINGDOCUMENTS: on
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_STAGINGDOCUMENTS: http://localhost:8080/minio/s3/stagingdocuments
    volumes:
      - minio_data:/data
    command: server /data --console-address :9090

  dynamodb:
    image: amazon/dynamodb-local:1.21.0
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/data

volumes:
  minio_data:
  dynamodb_data:
