AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FormKiQ Core - Console Install

Parameters:

  CertificateStackName:
    Type: String
    Description: The name of the FormKiQ Certificate Stack Name
    Default: ""

  HostedZoneId:
    Description: "Route53 Hosted Zone Id in which to add A record"
    Type: String
    Default: ""

  CloudFrontDistributionDomainName:
    Description: The cloudfront domain name of the resource
    Type: String
    Default: ""

Conditions:

  IsEmptyOrUnderscore:
    Fn::Or:
      - Fn::Equals:
          - Ref: HostedZoneId
          - ""
      - Fn::Equals:
          - Ref: HostedZoneId
          - "_"

  HasCertificateStackName:
    Fn::Not:
      - Fn::Equals:
          - Ref: CertificateStackName
          - ''

  HasHostedZoneId:
    Fn::Not:
      - Condition: IsEmptyOrUnderscore

Resources:

  CloudFrontDistributionRecordSet:
    Condition: HasHostedZoneId
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId:
        Ref: HostedZoneId
      RecordSets:
        - Name:
            Fn::ImportValue:
              Fn::Sub: '${CertificateStackName}-ConsoleDomain'
          Type: A
          AliasTarget:
            HostedZoneId: "Z2FDTNDATAQYW2"
            DNSName:
              Ref: CloudFrontDistributionDomainName
