#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FormKiQ Core - Console

Parameters:

  WAFWebACLId:
    Type: String
    Default: ""
    Description: (Optional) ARN of the AWS WAF WebACL to associate with the CloudFront distribution. Leave empty to disable.

  AdminEmail:
    Type: String
    Description: Administrator Email
    AllowedPattern: ".+"

  AppEnvironment:
    Type: String
    Description: The Document Stack Environment
    AllowedPattern: ".+"

  Domain:
    Description: Amazon Cognito domain to use (include full domain if CertificateArn used)
    Type: String

  ConsoleVersion:
    Type: String
    Description: Version of FormKiQ console to deploy
    Default: v4.0.33

  CognitoConfigBucket:
    Type: String
    Description: Cognito Config S3 Bucket

  FormKiQType:
    Description: The type of FormKiQ installation
    Type: String

  CertificateStackName:
    Type: String
    Description: The name of the FormKiQ Certificate Stack Name
    Default: ""

  CertificateStackNameDomainName:
    Type: String
    Description: The name of the FormKiQ Certificate Stack Name Domain Name
    Default: "_"

  IsGovCloud:
    Description: Is Installation AWS Region gov cloud
    Type: String
    AllowedValues: ["true", "false"]

  ApiUrl:
    Type: String
    Description: JWT API URL

  IamApiUrl:
    Type: String
    Description: IAM API URL

  KeyApiUrl:
    Type: String
    Description: Key API URL

  AuthApiUrl:
    Type: String
    Description: Auth Api URL

  Brand:
    Type: String
    Description: Console Installer Brand
    Default: "formkiq"

  AllowAdminCreateUserOnly:
    Description: When true only Cognito Admin can create users, false users can register themselves
    AllowedPattern: ".+"
    Type: String

  CognitoHostedUi:
    Description: Amazon Cognito Hosted UI Url
    AllowedPattern: ".+"
    Type: String

  CognitoUserPoolId:
    Description: The Cognito User Pool Id
    AllowedPattern: ".+"
    Type: String

  CognitoUserPoolClientId:
    Description: The Cognito User Pool Client Id
    AllowedPattern: ".+"
    Type: String

  UserAuthentication:
    Description: How are the users authenticating
    AllowedPattern: ".+"
    Type: String
    Default: "cognito"

  LogFormat:
    Description: >
      The format in which the application and system logs are stored.
    Type: String

  LogLevelApplication:
    Type: String
    Description: >
      The level of logging for the FormKiQ Application logs. Only used when LogFormat is JSON

  LogLevelSystem:
    Type: String
    Description: >
      The level of logging for the AWS Platform System logs. Only used when LogFormat is JSON

  LogRetentionInDays:
    Type: Number
    Description: The number of days to retain the log events

Conditions:
  HasWAF:
    Fn::Not:
      - Fn::Equals:
          - Ref: WAFWebACLId
          - ""

  HasCertificateStackName:
    Fn::Not:
      - Fn::Equals:
        - Ref: CertificateStackName
        - ''

  HasCertificateStackNameDomainName:
    Fn::Not:
      - Fn::Equals:
          - Ref: CertificateStackNameDomainName
          - '_'

  IsNotGovCloud:
    Fn::Equals:
      - Ref: IsGovCloud
      - 'false'

  IsLogFormatJSON:
    Fn::Equals:
      - Ref: LogFormat
      - JSON

Resources:

  WebUiConsole:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: "formkiq-${AppEnvironment}-web-ui-${AWS::AccountId}"
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Application
          Value: FormKiQ
        - Key: AppEnvironment
          Value:
            Fn::Sub: "${AppEnvironment}"

  ConsoleVersionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Console Version"
      Name:
        Fn::Sub: "/formkiq/${AppEnvironment}/console/version"
      Type: String
      Value:
        Ref: ConsoleVersion
      Tags:
        Application: "FormKiQ"
        AppEnvironment:
          Fn::Sub: "${AppEnvironment}"

  ConsoleParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Console S3 Bucket"
      Name:
        Fn::Sub: "/formkiq/${AppEnvironment}/s3/Console"
      Type: String
      Value:
        Ref: WebUiConsole
      Tags:
        Application: "FormKiQ"
        AppEnvironment:
          Fn::Sub: "${AppEnvironment}"

  ConsoleArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Console S3 Bucket Arn"
      Name:
        Fn::Sub: "/formkiq/${AppEnvironment}/s3/ConsoleArn"
      Type: String
      Value:
        Fn::GetAtt:
        - WebUiConsole
        - Arn
      Tags:
        Application: "FormKiQ"
        AppEnvironment:
          Fn::Sub: "${AppEnvironment}"

  ConsoleDomainNameParameter:
    Type: AWS::SSM::Parameter
    DependsOn:
    - WebUiConsole
    Properties:
      Description: "Console S3 Bucket Domain Name"
      Name:
        Fn::Sub: "/formkiq/${AppEnvironment}/s3/ConsoleDomainName"
      Type: String
      Value:
        Fn::GetAtt:
        - WebUiConsole
        - DomainName
      Tags:
        Application: "FormKiQ"
        AppEnvironment:
          Fn::Sub: "${AppEnvironment}"

  ConsoleRegionalDomainNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Console S3 Bucket Regional Domain Name"
      Name:
        Fn::Sub: "/formkiq/${AppEnvironment}/s3/ConsoleRegionalDomainName"
      Type: String
      Value:
        Fn::GetAtt:
        - WebUiConsole
        - RegionalDomainName
      Tags:
        Application: "FormKiQ"
        AppEnvironment:
          Fn::Sub: "${AppEnvironment}"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Condition: IsNotGovCloud
    Properties:
      DistributionConfig:
        Comment:
          Fn::Sub: "FormKiQ WebUi Console ${ConsoleVersion}"
        Origins:
        - DomainName:
            Fn::GetAtt:
            - WebUiConsole
            - RegionalDomainName
          Id: s3origin
          OriginPath:
            Fn::Sub: "/${ConsoleVersion}"
          OriginAccessControlId:
            Fn::GetAtt:
              - WebUiConsoleOAC
              - Id
          S3OriginConfig:
            OriginAccessIdentity: ''
        DefaultCacheBehavior:
          Compress: true
          DefaultTTL: 600
          MaxTTL: 600
          MinTTL: 0
          ForwardedValues:
            QueryString: false
          TargetOriginId: s3origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Aliases:
          Fn::If:
          - HasCertificateStackNameDomainName
          - Fn::Split:
              - ","
              - Fn::ImportValue:
                  Fn::Sub: '${CertificateStackName}-ConsoleDomain'
          - Ref: "AWS::NoValue"
        ViewerCertificate:
          AcmCertificateArn:
            Fn::If:
            - HasCertificateStackNameDomainName
            - Fn::ImportValue:
                Fn::Sub: '${CertificateStackName}-ConsoleCertificateArn'
            - Ref: "AWS::NoValue"
          SslSupportMethod:
            Fn::If:
            - HasCertificateStackNameDomainName
            - sni-only
            - Ref: "AWS::NoValue"
          MinimumProtocolVersion: TLSv1.2_2021
          CloudFrontDefaultCertificate:
            Fn::If:
            - HasCertificateStackNameDomainName
            - Ref: "AWS::NoValue"
            - 'true'
        Enabled: true
        WebACLId:
          Fn::If:
            - HasWAF
            - Ref: WAFWebACLId
            - Ref: AWS::NoValue
        HttpVersion: http2and3
        CustomErrorResponses:
        - ErrorCode: '403'
          ResponsePagePath: "/index.html"
          ResponseCode: '200'
        - ErrorCode: '404'
          ResponsePagePath: "/index.html"
          ResponseCode: '200'
      Tags:
        - Key: Application
          Value: "FormKiQ"
        - Key: AppEnvironment
          Value:
            Fn::Sub: "${AppEnvironment}"

  ConsoleUrlParameter:
    Type: AWS::SSM::Parameter
    Condition: IsNotGovCloud
    Properties:
      Description: "The URL for the FormKiQ Console"
      Name:
        Fn::Sub: "/formkiq/${AppEnvironment}/console/Url"
      Type: String
      Value:
        Fn::If:
          - HasCertificateStackNameDomainName
          - Fn::Join:
              - ""
              -
                - 'https://'
                - Ref: CertificateStackNameDomainName
          - Fn::Join:
              - ""
              -
                - 'https://'
                - Fn::GetAtt:
                    - CloudFrontDistribution
                    - DomainName
      Tags:
        Application: "FormKiQ"
        AppEnvironment:
          Fn::Sub: "${AppEnvironment}"

  WebUiConsoleOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name:
          Fn::Sub: "FormKiQ-WebUiConsole-${AppEnvironment}-Oac"
        Description: Access control for S3 origin
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  WebUiConsoleBucketPolicy:
    Condition: IsNotGovCloud
    Type: "AWS::S3::BucketPolicy"
    DependsOn:
    - WebUiConsole
    Properties:
      Bucket:
        Ref: WebUiConsole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - Fn::Sub: "arn:aws:s3:::${WebUiConsole}"
              - Fn::Sub: "arn:aws:s3:::${WebUiConsole}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"
          - Sid: AllowCloudFrontOACReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource:
              Fn::Sub: 'arn:aws:s3:::${WebUiConsole}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  ConsoleInstaller:
    Type: AWS::Serverless::Function
    Condition: IsNotGovCloud
    Properties:
      Handler: com.formkiq.stacks.console.ConsoleInstallHandler
      Description: Lambda function that Installs the FormKiQ Console
      Runtime: java17
      Timeout: 300
      MemorySize: 512
      AutoPublishCodeSha256: #@ data.values.hash or assert.fail("missing version")
      Role:
        Fn::GetAtt:
          - ConsoleInstallRole
          - Arn
      CodeUri: ./console-installer.zip
      Tags:
        Application: "FormKiQ"
        AppEnvironment:
          Fn::Sub: "${AppEnvironment}"
      Environment:
        Variables:
          CONSOLE_VERSION:
            Fn::Sub: "${ConsoleVersion}"
          REGION:
            Fn::Sub: "${AWS::Region}"
          CONSOLE_BUCKET:
            Fn::Sub: "${WebUiConsole}"
          COGNITO_CONFIG_BUCKET:
            Fn::Sub: "${CognitoConfigBucket}"
          CONSOLE_ZIP_URL:
            Fn::Sub: "https://formkiq-distribution-console.s3.us-east-1.amazonaws.com/formkiq-console/${ConsoleVersion}/formkiq-console.zip"
          API_URL:
            Ref: ApiUrl
          API_IAM_URL:
            Ref: IamApiUrl
          API_KEY_URL:
            Ref: KeyApiUrl
          API_AUTH_URL:
            Ref: AuthApiUrl
          BRAND:
            Fn::Sub: "${Brand}"
          ALLOW_ADMIN_CREATE_USER_ONLY:
            Fn::Sub: "${AllowAdminCreateUserOnly}"
          COGNITO_HOSTED_UI:
            Ref: CognitoHostedUi
          USER_AUTHENTICATION:
            Ref: UserAuthentication
          DOMAIN:
            Ref: Domain
          COGNITO_USER_POOL_CLIENT_ID:
            Ref: CognitoUserPoolClientId
          COGNITO_USER_POOL_ID:
            Ref: CognitoUserPoolId
      LoggingConfig:
        LogGroup:
          Ref: ConsoleInstallerLogGroup
        LogFormat:
          Ref: LogFormat
        ApplicationLogLevel:
          Fn::If:
            - IsLogFormatJSON
            - Ref: LogLevelApplication
            - Ref: AWS::NoValue
        SystemLogLevel:
          Fn::If:
            - IsLogFormatJSON
            - Ref: LogLevelSystem
            - Ref: AWS::NoValue

  ConsoleInstallerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays:
        Ref: LogRetentionInDays
      Tags:
        - Key: AppEnvironment
          Value:
            Ref: AppEnvironment
        - Key: Application
          Value: "FormKiQ"

  ConsoleInstallRole:
    Type: AWS::IAM::Role
    Condition: IsNotGovCloud
    Properties:
      Tags:
        - Key: "Application"
          Value: "FormKiQ"
        - Key: "AppEnvironment"
          Value:
            Fn::Sub: "${AppEnvironment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/
      Policies:
        -
          PolicyName:
            Fn::Sub: "${AWS::StackName}-ConsoleInstallPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - Fn::Sub: "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/formkiq/*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:ListBucketVersions
                  - s3:DeleteObjectVersion
                Resource:
                  - Fn::Join:
                      - ''
                      - - Fn::Sub: "arn:${AWS::Partition}:s3:::"
                        - Ref: WebUiConsole
                  - Fn::Join:
                      - ''
                      - - Fn::Sub: "arn:${AWS::Partition}:s3:::"
                        - Ref: WebUiConsole
                        - '/*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:ListBucketVersions
                  - s3:DeleteObjectVersion
                Resource:
                  - Fn::Join:
                      - ''
                      - - Fn::Sub: "arn:${AWS::Partition}:s3:::"
                        - Ref: CognitoConfigBucket
                  - Fn::Join:
                      - ''
                      - - Fn::Sub: "arn:${AWS::Partition}:s3:::"
                        - Ref: CognitoConfigBucket
                        - '/*'
              - Effect: Allow
                Action:
                  - 'kms:Encrypt'
                  - 'kms:Decrypt'
                  - 'kms:ReEncrypt*'
                  - 'kms:GenerateDataKey*'
                  - 'kms:DescribeKey'
                Resource: '*'

  ConsoleInstallerRef:
    Type: Custom::ConsoleInstallerRef
    Condition: IsNotGovCloud
    Properties:
      Nonce:
        Ref: ConsoleVersion
      API_URL:
        Ref: ApiUrl
      API_IAM_URL:
        Ref: IamApiUrl
      API_KEY_URL:
        Ref: KeyApiUrl
      API_AUTH_URL:
        Ref: AuthApiUrl
      HttpApiUrl:
        Fn::If:
          - HasCertificateStackName
          - Fn::ImportValue:
              Fn::Sub: '${CertificateStackName}-HttpApiDomain'
          - ''
      IamApiUrl:
        Fn::If:
          - HasCertificateStackName
          - Fn::ImportValue:
              Fn::Sub: '${CertificateStackName}-IamApiDomain'
          - ''
      ServiceToken:
        Fn::GetAtt:
          - ConsoleInstaller
          - Arn

Outputs:

  ConsoleUrl:
    Description: Console URL
    Value:
      Fn::If:
      - HasCertificateStackNameDomainName
      - Fn::Join:
          - ""
          -
            - 'https://'
            - Ref: CertificateStackNameDomainName
      - Fn::If:
        - IsNotGovCloud
        - Fn::Join:
            - ""
            -
              - 'https://'
              - Fn::GetAtt:
                - CloudFrontDistribution
                - DomainName
        - "none"

  ConsoleBucket:
    Value:
      Ref: WebUiConsole

  ConsoleVersion:
    Value:
      Ref: ConsoleVersion

  HostedZoneId:
    Value:
      Fn::If:
      - HasCertificateStackName
      - Fn::ImportValue:
          Fn::Sub: '${CertificateStackName}-HostedZoneId'
      - ""

  CloudFrontDistributionDomainName:
    Value:
      Fn::If:
      - IsNotGovCloud
      - Fn::GetAtt:
        - CloudFrontDistribution
        - DomainName
      - ""
