AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FormKiQ - Email Notify Module
        
Parameters:

  AppEnvironment:
    Type: String
    Description: The Application Environment
    AllowedPattern: ".+"
    
  Email:
    Type: String
    Description: Email (required)
    AllowedPattern: ".+"

  FormKiQType:
    Description: The type of FormKiQ installation
    Default: "core"
    Type: String
    AllowedValues: ["core", "enterprise"]
    
Resources:
            
  DocumentsEmailNotification:
    Type: "AWS::SNS::Topic"
    Properties:
      Tags:
        - Key: "Application"
          Value: 
            Fn::Sub: "FormKiQ ${FormKiQType}"      
        - Key: "AppEnvironment"
          Value: 
            Fn::Sub: "${AppEnvironment}"
        - Key: "StackName"
          Value: 
            Fn::Sub: "${AWS::StackName}" 

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties: 
      Endpoint: 
        Ref: Email
      Protocol: "email"
      TopicArn: 
        Ref: DocumentsEmailNotification
      
  SnsDocumentsEmailNotificationArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "SNS Topic for Email Notification"
      Name: 
        Fn::Sub: "/formkiq/${AppEnvironment}/sns/DocumentsEmailNotificationArn"
      Type: String
      Value: 
        Ref: DocumentsEmailNotification
      Tags:
        Application: 
          Fn::Sub: "FormKiQ ${FormKiQType}"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"

  Module:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../module-documentevent.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
      Tags:
        Application: 
          Fn::Sub: "FormKiQ ${FormKiQType}"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"
        
  EmailNotify:
    Type: AWS::Serverless::Function
    DependsOn:
    - EmailNotifyRole
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 60
      MemorySize: 256
      CodeUri: ./module-email-notify.zip
      AutoPublishCodeSha256: 0E88FEF466DE7769DD559283C1443B7B62D03CA56B0FFC9128F93ABA919BFDF2
      Environment:
        Variables:
          DEBUG: false
          EMAIL_TOPIC_ARN: 
            Ref: DocumentsEmailNotification
          CONSOLE_URL: 
            Fn::Sub: "{{resolve:ssm:/formkiq/${AppEnvironment}/console/Url}}" 
      Role: 
        Fn::GetAtt: 
        - EmailNotifyRole
        - Arn
      Tags:
        Application: 
          Fn::Sub: "FormKiQ ${FormKiQType}"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
      Events:
        CreateSQSEvent:
          Type: SQS
          Properties:
            Queue: 
              Fn::GetAtt: 
              - Module
              - Outputs.SqsQueueArn
            BatchSize: 10
      
  EmailNotifyRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: "Application"
          Value: 
            Fn::Sub: "FormKiQ ${FormKiQType}"
        - Key: "AppEnvironment"
          Value: 
            Fn::Sub: "${AppEnvironment}"
        - Key: StackName
          Value: 
            Fn::Sub: "${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: EmailNotificationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: "*"
            - Effect: Allow
              Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              Resource:
              - Fn::GetAtt: 
                - Module
                - Outputs.SqsQueueArn
            - Effect: Allow
              Action:
              - sns:Publish
              Resource:
              - Ref: DocumentsEmailNotification              