AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FormKiQ - Email Notify Module

Metadata:
  AWS::ServerlessRepo::Application:
    Name: FormKiQ-Module-Email-Nodify
    Description: Base component of FormKiQ-Core
    Author: FormKiQ Inc
    SpdxLicenseId: MIT
    LicenseUrl: file://../../../LICENSE
    ReadmeUrl: file://../../../README.md
    Labels: []
    HomePageUrl: https://github.com/formkiq/formkiq-core
    SourceCodeUrl: https://github.com/formkiq/formkiq-core
        
Parameters:

  AppEnvironment:
    Type: String
    Description: The Application Environment
    AllowedPattern: ".+"
    
  Email:
    Type: String
    Description: Email (required)
    AllowedPattern: ".+"

  FormKiQType:
    Description: The type of FormKiQ installation
    Default: "core"
    Type: String
    AllowedValues: ["core", "pro"]
    
Resources:
            
  DocumentsEmailNotification:
    Type: "AWS::SNS::Topic"
    Properties:
      Tags:
        - Key: "Application"
          Value: !Sub "FormKiQ ${FormKiQType}"      
        - Key: "AppEnvironment"
          Value: !Sub "${AppEnvironment}"
        - Key: "StackName"
          Value: !Sub "${AWS::StackName}" 

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties: 
      Endpoint: !Ref Email
      Protocol: "email"
      TopicArn: !Ref DocumentsEmailNotification
      
  SnsDocumentsEmailNotificationArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "SNS Topic for Document Create Events"
      Name: !Sub "/formkiq/${AppEnvironment}/sns/DocumentsEmailNotificationArn"
      Type: String
      Value: !Ref DocumentsEmailNotification
      Tags:
        Application: !Sub "FormKiQ ${FormKiQType}"
        AppEnvironment: !Sub "${AppEnvironment}"
        StackName: !Sub "${AWS::StackName}"

  Module:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../module-documentevent.yaml
      Parameters:
        AppEnvironment: !Ref AppEnvironment
      Tags:
        Application: !Sub "FormKiQ ${FormKiQType}"
        AppEnvironment: !Sub "${AppEnvironment}"
        StackName: !Sub "${AWS::StackName}"
        
  EmailNotify:
    Type: AWS::Serverless::Function
    DependsOn:
    - EmailNotifyRole
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 60
      MemorySize: 256
      CodeUri: ./module-email-notify.zip
      Environment:
        Variables:
          DEBUG: false
          EMAIL_TOPIC_ARN: !Ref DocumentsEmailNotification
          CONSOLE_URL: !Sub "{{resolve:ssm:/formkiq/${AppEnvironment}/console/Url:1}}" 
      Role: !GetAtt [EmailNotifyRole, Arn]
      Tags:
        Application: !Sub "FormKiQ ${FormKiQType}"
        AppEnvironment: !Sub "${AppEnvironment}"
      Events:
        CreateSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt Module.Outputs.SqsQueueArn
            BatchSize: 10
      
  EmailNotifyRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: "Application"
          Value: !Sub "FormKiQ ${FormKiQType}"
        - Key: "AppEnvironment"
          Value: !Sub "${AppEnvironment}"
        - Key: StackName
          Value: !Sub "${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: EmailNotificationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: "*"
            - Effect: Allow
              Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              Resource:
              - !GetAtt Module.Outputs.SqsQueueArn
            - Effect: Allow
              Action:
              - sns:Publish
              Resource:
              - !Ref DocumentsEmailNotification              