
description = "FormKiQ Actions"

dependencies {

  implementation libs.ulid.creator

  implementation project(':adapters:aws:dynamodb')
  implementation project(':domain:document-events')
  implementation project(':libs:lambda-services')
  implementation project(':libs:validation')

  testImplementation project(':domain:documents')
  testImplementation project(':testing:test-utils')
  testImplementation project(':adapters:aws:s3')
  testImplementation libs.junit.jupiter.engine
  testRuntimeOnly  libs.junit.platform.launcher
}
