AWSTemplateFormatVersion: '2010-09-09'
Description: FormKiQ Core - Console Users.

Parameters:

  AppEnvironment:
    Type: String
    Description: The Application Environment
    AllowedPattern: ".+"
    
  AdminEmail:
    Type: String
    Description: Administrator Email
    AllowedPattern: ".+"
     
Resources:

  ConsoleAdminUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      DesiredDeliveryMediums: 
        - EMAIL
      Username: !Sub "${AdminEmail}"
      UserPoolId: !Sub "{{resolve:ssm:/formkiq/${AppEnvironment}/cognito/UserPoolId:1}}"
      UserAttributes:
        - Name: email
          Value: !Sub "${AdminEmail}"
        - Name: email_verified
          Value: "true"

  ConsoleAddUserToGroup:
    Type: AWS::Cognito::UserPoolUserToGroupAttachment
    DependsOn:
    - ConsoleAdminUser
    Properties: 
      GroupName: !Sub "{{resolve:ssm:/formkiq/${AppEnvironment}/cognito/AdminGroup:1}}"
      Username: !Sub "${AdminEmail}"
      UserPoolId: !Sub "{{resolve:ssm:/formkiq/${AppEnvironment}/cognito/UserPoolId:1}}"

  ConsoleAddUserToDefaultGroup:
    Type: AWS::Cognito::UserPoolUserToGroupAttachment
    DependsOn:
    - ConsoleAdminUser
    Properties: 
      GroupName: "default"
      Username: !Sub "${AdminEmail}"
      UserPoolId: !Sub "{{resolve:ssm:/formkiq/${AppEnvironment}/cognito/UserPoolId:1}}"
      
  ConsoleAdminEmailParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Console Admin Email"
      Name: !Sub "/formkiq/${AppEnvironment}/console/AdminEmail"
      Type: String
      Value: !Ref AdminEmail
      Tags:
        Application: "FormKiQ Stacks - Document"
        AppEnvironment: !Sub "${AppEnvironment}"
        
Outputs:
  ConsoleAdminEmail:
    Value: !Ref AdminEmail