AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FormKiQ Core - Console Install
        
Parameters:
    
  AppEnvironment:
    Type: String
    Description: The Document Stack Environment
    AllowedPattern: ".+"
          
  ConsoleVersion:
    Type: String
    Description: Version of FormKiQ console to deploy
    AllowedPattern: ".+"
 
  Domain:
    Description: Amazon Cognito domain to use (include full domain if CertificateArn used)
    AllowedPattern: ".+"
    Type: String
    
  ConsoleBucket:
    Type: String
    Description: Console S3 Bucket
    AllowedPattern: ".+"

  CognitoConfigBucket:
    Type: String
    Description: Cognito Config S3 Bucket
    AllowedPattern: ".+"

  ApiUrl:
    Type: String
    Description: API URL
    AllowedPattern: ".+"  
  
  WebsocketApiUrl:
    Type: String
    Description: WebSocket URL
    AllowedPattern: ".+" 
 
  AuthApiUrl:
    Type: String
    Description: Auth Api URL
    AllowedPattern: ".+" 

  Brand:
    Type: String
    Description: Console Installer Brand
    Default: "formkiq"
    
  DistributionBucket:
    Type: String
    Description: FormKiQ Distribution BucketName
    Default: "formkiq-distribution-console"

  FormKiQType:
    Description: The type of FormKiQ installation
    Default: "core"
    Type: String
    AllowedValues: ["core", "enterprise"]

  AllowAdminCreateUserOnly:
    Description: When true only Cognito Admin can create users, false users can register themselves
    AllowedPattern: ".+"
    Type: String
    
  CognitoHostedUi:
    Description: Amazon Cognito Hosted UI Url
    AllowedPattern: ".+"
    Type: String

  CognitoUserPoolId:
    Description: The Cognito User Pool Id
    AllowedPattern: ".+"
    Type: String
    
  CognitoUserPoolClientId:
    Description: The Cognito User Pool Client Id
    AllowedPattern: ".+"
    Type: String
    
  UserAuthentication:
    Description: How are the users authenticating
    AllowedPattern: ".+"
    Type: String
    Default: "cognito"
    
  CertificateStackName:
    Type: String
    Description: The name of the FormKiQ Certificate Stack Name
    Default: ""

  HostedZoneId:
    Description: "Route53 Hosted Zone Id in which to add A record"
    Type: String
    Default: ""
    
  CloudFrontDistributionDomainName:
    Description: The cloudfront domain name of the resource
    Type: String
    Default: ""
    
  Partition:
    Description: The partition in which the resource is located. A partition is a group of AWS Regions
    Type: String

  IsGovCloud:
    Description: Is Installation AWS Region gov cloud
    Type: String
    AllowedValues: ["true", "false"]
    
Conditions:

  HasCertificateStackName:
    Fn::Not:
      - Fn::Equals: 
        - Ref: CertificateStackName
        - ''

  HasHostedZoneId:
    Fn::Not:
      - Fn::Equals: 
        - Ref: HostedZoneId
        - ''

  IsNotGovCloud:
    Fn::Equals: 
      - Ref: IsGovCloud
      - 'false'

Resources:

  ConsoleInstallerParameter:
    Condition: IsNotGovCloud
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Lambda for Console Installation"
      Name: 
        Fn::Sub: "/formkiq/${AppEnvironment}/lambda/ConsoleInstaller"
      Type: String
      Value: 
        Ref: ConsoleInstaller
      Tags:
        Application: 
          Fn::Sub: "FormKiQ ${FormKiQType}"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"

  ConsoleInstaller:
    Type: AWS::Serverless::Function
    Condition: IsNotGovCloud
    Properties:
      Handler: com.formkiq.stacks.console.ConsoleInstallHandler
      Description: Lambda function that Installs the FormKiQ Console
      Runtime: java11
      Timeout: 300
      MemorySize: 512
      Role:
        Fn::GetAtt:
        - ConsoleInstallRole
        - Arn
      CodeUri: ./console-installer.zip
      Tags:
        Application: 
          Fn::Sub: "FormKiQ ${FormKiQType}"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"
      Environment:
        Variables:
          CONSOLE_VERSION: 
            Fn::Sub: "${ConsoleVersion}"
          DISTRIBUTION_BUCKET: 
            Fn::Sub: "${DistributionBucket}"
          REGION: 
            Fn::Sub: "${AWS::Region}"
          CONSOLE_BUCKET: 
            Fn::Sub: "${ConsoleBucket}"
          COGNITO_CONFIG_BUCKET:
            Fn::Sub: "${CognitoConfigBucket}"
          API_URL: 
            Fn::Sub: "${ApiUrl}"
          API_WEBSOCKET_URL: 
            Fn::Sub: "${WebsocketApiUrl}"
          API_AUTH_URL: 
            Fn::Sub: "${AuthApiUrl}"
          BRAND: 
            Fn::Sub: "${Brand}"
          ALLOW_ADMIN_CREATE_USER_ONLY: 
            Fn::Sub: "${AllowAdminCreateUserOnly}"
          COGNITO_HOSTED_UI:
            Ref: CognitoHostedUi
          USER_AUTHENTICATION:
            Ref: UserAuthentication
          DOMAIN:
            Ref: Domain
          COGNITO_USER_POOL_CLIENT_ID:
            Ref: CognitoUserPoolClientId
          COGNITO_USER_POOL_ID:
            Ref: CognitoUserPoolId

  ConsoleInstallRole:
    Type: AWS::IAM::Role
    Condition: IsNotGovCloud
    Properties:
      Tags:
        - Key: "Application"
          Value: 
            Fn::Sub: "FormKiQ ${FormKiQType}"        
        - Key: "AppEnvironment"
          Value: 
            Fn::Sub: "${AppEnvironment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: 
            Fn::Sub: "${AWS::StackName}-ConsoleInstallPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: "*"
            - Effect: Allow
              Action:
              - ssm:GetParameter
              Resource: 
              - Fn::Sub: "arn:${Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/formkiq/*"
            - Effect: Allow
              Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
              Resource: 
              - Fn::Join:
                - ''
                - - Fn::Sub: "arn:${Partition}:s3:::"
                  - Ref: ConsoleBucket
              - Fn::Join:
                - ''
                - - Fn::Sub: "arn:${Partition}:s3:::"
                  - Ref: ConsoleBucket
                  - '/*'
            - Effect: Allow
              Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
              Resource:
              - Fn::Join:
                - ''
                - - Fn::Sub: "arn:${Partition}:s3:::"
                  - Ref: CognitoConfigBucket
              - Fn::Join:
                - ''
                - - Fn::Sub: "arn:${Partition}:s3:::"
                  - Ref: CognitoConfigBucket
                  - '/*'
            - Effect: Allow
              Action:
              - s3:GetObject
              Resource: 
              - Fn::Join:
                - ''
                - - Fn::Sub: "arn:${Partition}:s3:::"
                  - Ref: DistributionBucket
                  - '/*'
            - Effect: Allow
              Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
              Resource: '*'

  ConsoleInstallerRef:
    Type: Custom::ConsoleInstallerRef
    Condition: IsNotGovCloud
    Properties:
      Nonce:
        Ref: ConsoleVersion
      HttpApiUrl:
        Fn::If:
          - HasCertificateStackName
          - Fn::ImportValue:
              Fn::Sub: '${CertificateStackName}-HttpApiDomain'
          - ''
      IamApiUrl:
        Fn::If:
          - HasCertificateStackName
          - Fn::ImportValue:
              Fn::Sub: '${CertificateStackName}-IamApiDomain'
          - ''
      ServiceToken:
        Fn::GetAtt:
        - ConsoleInstaller
        - Arn

  CloudFrontDistributionRecordSet:
    Condition: HasHostedZoneId
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: 
        Ref: HostedZoneId
      RecordSets:
        - Name:
            Fn::ImportValue:
              Fn::Sub: '${CertificateStackName}-ConsoleDomain'
          Type: A
          AliasTarget:
            HostedZoneId: "Z2FDTNDATAQYW2"
            DNSName: 
              Ref: CloudFrontDistributionDomainName