AWSTemplateFormatVersion: '2010-09-09'
Description: FormKiQ Config

Parameters:

  FormKiQType:
    Type: String
    Description: The formkiq type of installation
    AllowedPattern: ".+"

  FormKiQVersion:
    Type: String
    Description: The formkiq version
    AllowedPattern: ".+"

  VpcStackName:
    Type: String
    Description: >
      The name of the CloudFormation VPC stack that can be created after the initial FormKiQ install, using the add-on CloudFormation template for VPC https://docs.formkiq.com/docs/getting-started/quick-start#create-vpc.
      Some services such as Typesense, and OpenSearch require a VPC. Only required if you are using any of these services; otherwise, this can remain empty.

Conditions:
  HasVpcStackName:
    Fn::Not:
      - Fn::Equals:
          - Ref: VpcStackName
          - ''

Resources:
  PlaceholderResource:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:

  FormKiQType:
    Description: The FormKiQ type of installation
    Value:
      Ref: FormKiQType

  FormKiQVersion:
    Description: The FormKiQ version
    Value:
      Ref: FormKiQVersion
