AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FormKiQ Core

Parameters:

  AdminEmail:
    Type: String
    Description: Administrator Email (required)
    AllowedPattern: ".+"

  AppEnvironment:
    Type: String
    Description: Unique Application Environment Identifier, IE dev/staging/prod
    Default: prod
        
  LambdaMemoryForApiGateway:
    Type: Number
    Description: Memory (in MB) of the API Gateway Lambda - 512 MB is recommended
    Default: 512
    MinValue: 128
    MaxValue: 3008
  
  EnablePublicUrls:
    Description: Enables /public urls (unauthenticated urls)
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]
  
  LambdaMemoryForS3:
    Type: Number
    Description: Memory (in MB) of the Document Procesor - 512 MB is recommended, unless dealing with > 1 GB files
    Default: 512
    MinValue: 128
    MaxValue: 3008
    
  PasswordMinimumLength:
    Type: Number
    Description: The minimum password length for FormKiQ Stacks Cognito Users
    MinValue: "6"
    MaxValue: "99"
    Default: "8"
    
  PasswordRequireLowercase:
    Description: Whether FormKiQ Stacks Cognito Users password requires at least one lowercase letter
    Default: "true"
    Type: String
    AllowedValues: ["true", "false"]
    
  PasswordRequireNumbers:
    Description: Whether FormKiQ Stacks Cognito Users password requires at least one number
    Default: "true"
    Type: String
    AllowedValues: ["true", "false"]
    
  PasswordRequireSymbols:
    Description: Whether FormKiQ Stacks Cognito Users password requires at least one symbol
    Default: "true"
    Type: String
    AllowedValues: ["true", "false"]
    
  PasswordRequireUppercase:
    Description: Whether FormKiQ Stacks Cognito Users password requires at least one uppercase letter
    Default: "true"
    Type: String
    AllowedValues: ["true", "false"]
     
Resources:

  VersionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "FormKiQ Stacks Version"
      Name: !Sub "/formkiq/${AppEnvironment}/version"
      Type: String
      Value: "2.0.0"
      
  RegionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Installation Region"
      Name: !Sub "/formkiq/${AppEnvironment}/region"
      Type: String
      Value: !Ref "AWS::Region"
  
  DocumentsApiCognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../../../lambda-api/src/main/resources/cloudformation/cognito-api-gateway.yml
      Parameters:
        AppEnvironment: !Sub "${AppEnvironment}"
        PasswordMinimumLength: !Sub "${PasswordMinimumLength}"
        PasswordRequireLowercase: !Sub "${PasswordRequireLowercase}"
        PasswordRequireNumbers: !Sub "${PasswordRequireNumbers}"
        PasswordRequireSymbols: !Sub "${PasswordRequireSymbols}"
        PasswordRequireUppercase: !Sub "${PasswordRequireUppercase}"
 
  Console:
    Type: AWS::Serverless::Application
    DependsOn:
      - DocumentsApi
    Properties:
      Location: ../../../../console/src/main/resources/cloudformation/console.yml
      TimeoutInMinutes: 5
      Parameters:
        AppEnvironment: !Sub "${AppEnvironment}"

  ConsoleUsers:
    Type: AWS::Serverless::Application
    DependsOn:
      - Console
      - ConsoleCloudfront
    Properties:
      Location: ../../../../console/src/main/resources/cloudformation/console-users.yml
      Parameters:
        AdminEmail: !Sub "${AdminEmail}"
        AppEnvironment: !Sub "${AppEnvironment}"
        
  ConsoleCloudfront:
    Type: AWS::Serverless::Application
    DependsOn:
      - Console
    Properties:
      Location: ../../../../console/src/main/resources/cloudformation/cloudfront.yml
      Parameters:
        AppEnvironment: !Sub "${AppEnvironment}"
        ConsoleVersion: !GetAtt Console.Outputs.ConsoleVersion
                 
  DocumentsDynamodb:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../../../dynamodb-documents/src/main/resources/cloudformation/dynamodb-documents.yml
      Parameters:
        AppEnvironment: !Sub "${AppEnvironment}"

  DocumentsBuckets:
    Type: AWS::Serverless::Application
    DependsOn:
      - DocumentsDynamodb
    Properties:
      Location: ../../../../lambda-s3/src/main/resources/cloudformation/lambda-s3.yml
      Parameters:
        AppEnvironment: !Sub "${AppEnvironment}"
        LambdaMemory: !Sub "${LambdaMemoryForS3}"

  DocumentsApi:
    Type: AWS::Serverless::Application
    DependsOn:
      - DocumentsApiCognito
      - DocumentsBuckets
    Properties:
      Location: ../../../../lambda-api/src/main/resources/cloudformation/lambda-api.yml
      Parameters:
        AppEnvironment: !Sub "${AppEnvironment}"
        CognitoPoolId: !GetAtt DocumentsApiCognito.Outputs.CognitoUserPoolId
        LambdaMemory: !Sub "${LambdaMemoryForApiGateway}"
        EnablePublicUrls: !Ref EnablePublicUrls
        
Outputs:
  IamApiUrl:
    Description: "The endpoint url for the IAM API"
    Value: !GetAtt DocumentsApi.Outputs.DocumentsIamApiUrl
  HttpApiUrl:
    Description: "The endpoint url for the Http API"
    Value: !GetAtt DocumentsApi.Outputs.DocumentsHttpApiUrl
  ConsoleUrl:
    Description: Console URL
    Value: !GetAtt ConsoleCloudfront.Outputs.CloudFrontDistributionUrl
  