AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FormKiQ Event Messaging

Parameters:

  AppEnvironment:
    Type: String
    Description: Unique Application Environment Identifier, IE dev/staging/prod
    AllowedPattern: ".+"

Resources:

  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name:
        Fn::Sub: "formkiq-${AppEnvironment}"

Outputs:

  EventBusName:
    Description: Name EventBridge Event Bus
    Value:
      Ref: EventBus
