AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FormKiQ Event Messaging

Parameters:

  AppEnvironment:
    Type: String
    Description: Unique Application Environment Identifier, IE dev/staging/prod
    AllowedPattern: ".+"

Resources:

  DocumentEventsBus:
    Type: AWS::Events::EventBus
    Properties:
      Name:
        Fn::Sub: "FormKiQ-DocumentEvents-${AppEnvironment}"

  EventInternalBus:
    Type: AWS::Events::EventBus
    Properties:
      Name:
        Fn::Sub: "FormKiQ-InternalEvents-${AppEnvironment}"

Outputs:

  DocumentEventsBus:
    Description: Name EventBridge Event Bus
    Value:
      Ref: DocumentEventsBus
      
  EventInternalBus:
    Description: Name EventBridge Event Bus
    Value:
      Ref: EventInternalBus
