#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: #@ "FormKiQ Core " + data.values.version or assert.fail("missing version")
    
Parameters:

  AdminEmail:
    Type: String
    Description: Administrator Email (required)
    AllowedPattern: ".+"

  AppEnvironment:
    Type: String
    Description: Unique Application Environment Identifier, IE dev/staging/prod
    AllowedPattern: "[a-zA-Z0-9_.-/]+"
    Default: prod
  
  EnablePublicUrls:
    Description: Enables /public urls (unauthenticated urls)
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]
    
  PasswordMinimumLength:
    Type: Number
    Description: The minimum password length for FormKiQ Cognito Users
    MinValue: "6"
    MaxValue: "99"
    Default: "8"
    
  PasswordRequireLowercase:
    Description: Whether FormKiQ Cognito Users password requires at least one lowercase letter
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]
    
  PasswordRequireNumbers:
    Description: Whether FormKiQ Cognito Users password requires at least one number
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]
    
  PasswordRequireSymbols:
    Description: Whether FormKiQ Cognito Users password requires at least one symbol
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]
    
  PasswordRequireUppercase:
    Description: Whether FormKiQ Cognito Users password requires at least one uppercase letter
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]

  VpcStackName:
    Type: String
    Description: (optional) FormKiQ VPC Stack Name 
    Default: ""

  TypesenseApiKey:
    Type: String
    Description: (optional) Random string of characters for https://typesense.org API access 
    Default: ""

  CapacityProvider:
    Description: AWS Fargate capacity provider to use, either the FARGATE or FARGATE_SPOT 
    Default: "FARGATE_SPOT"
    Type: String
    AllowedValues: ["FARGATE_SPOT", "FARGATE"]
    
Resources:

  EditionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "FormKiQ Edition"
      Name: 
        Fn::Sub: "/formkiq/${AppEnvironment}/edition"
      Type: String
      Value: "core"
      Tags:
        Application: "FormKiQ Core"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"
          
  VersionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "FormKiQ Version"
      Name: 
        Fn::Sub: "/formkiq/${AppEnvironment}/version"
      Type: String
      Value: #@ data.values.version or assert.fail("missing version")
      Tags:
        Application: "FormKiQ Core"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"
      
  RegionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Installation Region"
      Name: 
        Fn::Sub: "/formkiq/${AppEnvironment}/region"
      Type: String
      Value: 
        Ref: "AWS::Region"
      Tags:
        Application: "FormKiQ Core"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"

  CoreStorage:
    Type: AWS::Serverless::Application
    Properties:
      Location: storage/template.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
      Tags:
        Application: "FormKiQ Core"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"

  CoreConsole:
    Type: AWS::Serverless::Application
    Properties:
      Location: console/template.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
        AdminEmail: 
          Ref: AdminEmail
      Tags:
        Application: "FormKiQ Core"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"

  CoreConsoleInstall:
    Type: AWS::Serverless::Application
    DependsOn:
      - CoreApi
      - Cognito
    Properties:
      Location: console/template-install.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
        ConsoleVersion: 
          Fn::GetAtt: 
          - CoreConsole
          - Outputs.ConsoleVersion
        ConsoleBucket: 
          Fn::GetAtt: 
          - CoreConsole
          - Outputs.ConsoleBucket
        ApiUrl: 
          Fn::GetAtt: 
          - CoreApi
          - Outputs.DocumentsHttpApiUrl
        WebsocketApiUrl: 
          Fn::GetAtt: 
          - WebsocketApi
          - Outputs.WebsocketApiUrl
        AuthApiUrl: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.ApiEndpoint
        AllowAdminCreateUserOnly: "true"
        CognitoHostedUi:
          Fn::GetAtt:
          - Cognito
          - Outputs.CognitoHostedUi
        CognitoUserPoolId:
          Fn::GetAtt:
          - Cognito
          - Outputs.CognitoUserPoolId
        CognitoUserPoolClientId:
          Fn::GetAtt:
          - Cognito
          - Outputs.CognitoUserPoolClientId
        CognitoConfigBucket:
          Fn::GetAtt:
          - Cognito
          - Outputs.CognitoConfigBucket
        Domain:
          Fn::GetAtt:
          - Cognito
          - Outputs.Domain
      Tags:
        Application: "FormKiQ Core"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"

  Cognito:
    Type: AWS::Serverless::Application
    DependsOn:
      - CoreConsole
    Properties:
      Location: cognito/template.yaml
      Parameters:
        UserPoolName: 
          Fn::Sub: "${AWS::StackName}-${AppEnvironment}"
        AllowAdminCreateUserOnly: "true"
        PasswordMinimumLength: 
          Fn::Sub: "${PasswordMinimumLength}"
        PasswordRequireLowercase: 
          Fn::Sub: "${PasswordRequireLowercase}"
        PasswordRequireNumbers: 
          Fn::Sub: "${PasswordRequireNumbers}"
        PasswordRequireSymbols: 
          Fn::Sub: "${PasswordRequireSymbols}"
        PasswordRequireUppercase: 
          Fn::Sub: "${PasswordRequireUppercase}"
        Domain: 
          Fn::Sub: "${AppEnvironment}${AWS::AccountId}"
        RedirectUrl:
          Fn::GetAtt:
          - CoreConsole
          - Outputs.ConsoleUrl
      Tags:
        Application: "FormKiQ Core"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"
        
  SsmProperties:
    Type: AWS::Serverless::Application
    DependsOn:
      - Cognito
    Properties:
      Location: ./ssm-template.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
        CognitoUserPool: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolId
        CognitoUserPoolArn: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolArn
        CognitoUserPoolClient: 
          Fn::GetAtt:
          - Cognito
          - Outputs.CognitoUserPoolClientId
        CognitoIdentityPool: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoIdentityPoolId
        Domain: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.Domain
        
  CoreApi:
    Type: AWS::Serverless::Application
    DependsOn:
      - Cognito
      - WebsocketApi
      - TypeSenseService
    Properties:
      Location: api/template.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
        EnablePublicUrls: 
          Ref: EnablePublicUrls
        PasswordMinimumLength: 
          Ref: PasswordMinimumLength
        PasswordRequireLowercase: 
          Ref: PasswordRequireLowercase
        PasswordRequireNumbers: 
          Ref: PasswordRequireNumbers
        PasswordRequireSymbols: 
          Ref: PasswordRequireSymbols
        PasswordRequireUppercase: 
          Ref: PasswordRequireUppercase
        CognitoUserPool: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolId
        CognitoUserPoolClient: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolClientId
        WebsocketSqsQueueUrl: 
          Fn::GetAtt: 
          - WebsocketApi
          - Outputs.SqsQueueUrl
        TypesenseApiKey: 
          Ref: TypesenseApiKey
        TypesenseApiEndpoint:
          Fn::GetAtt:
          - TypeSenseService
          - Outputs.TypesenseApiEndpoint
        VpcStackName:
          Ref: VpcStackName
      Tags:
        Application: "FormKiQ Core"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"

  CoreConsoleUsers:
    Type: AWS::Serverless::Application
    DependsOn:
      - CoreApi
      - SsmProperties
      - CoreConsoleInstall
    Properties:
      Location: console/template-users.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
        AdminEmail: 
          Ref: AdminEmail
        CognitoUserPool: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolId
        CognitoUserPoolArn: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolArn
        CognitoIdentityPool: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoIdentityPoolId
        CognitoUserPoolClient: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolClientId
      Tags:
        Application: "FormKiQ Core"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"
          
  WebsocketApi:
    Type: AWS::Serverless::Application
    DependsOn:
      - Cognito
    Properties:
      Location: websocket-api/template.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
        CognitoUserPoolId: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolId
        CognitoUserPoolClientId: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolClientId
      Tags:
        Application: "FormKiQ Core"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"

  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName:
        Fn::Sub: "FormKiQ-${AppEnvironment}"
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider:
            Ref: CapacityProvider
          Weight: 1
      Tags:
        - Key: "Application"
          Value: 
            Fn::Sub: "FormKiQ"        
        - Key: "AppEnvironment"
          Value: 
            Fn::Sub: "${AppEnvironment}"
        - Key: "StackName"
          Value: 
            Fn::Sub: "${AWS::StackName}"
            
  TypeSenseService:
    Type: AWS::Serverless::Application
    DependsOn:
      - ECSCluster
      - CoreStorage
    Properties:
      Location: typesense/template.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
        TypesenseApiKey:
          Ref: TypesenseApiKey
        VpcStackName:
          Ref: VpcStackName
        ECSCluster:
          Ref: ECSCluster
      Tags:
        Application: "FormKiQ Core"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"

  TypesenseApiKeyParameter:
    Type: AWS::SSM::Parameter
    Condition: CreateResources
    Properties:
      Description: "Typesense API Key"
      Name: 
        Fn::Sub: "/formkiq/${AppEnvironment}/typesense/ApiKey"
      Type: String
      Value:
        Ref: TypesenseApiKey
      Tags:
        Application: 
          Fn::Sub: "FormKiQ ${FormKiQType}"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"
          
Outputs:
  AppEnvironment:
    Description: Unique Application Environment Identifier, IE dev/staging/prod
    Value: 
      Ref: AppEnvironment
  IamApiUrl:
    Description: "The URL for the API endpoint that uses IAM authorization"
    Value: 
      Fn::GetAtt: 
      - CoreApi
      - Outputs.DocumentsIamApiUrl
  HttpApiUrl:
    Description: "The URL for the API endpoint that uses Cognito authorization"
    Value: 
      Fn::GetAtt: 
      - CoreApi
      - Outputs.DocumentsHttpApiUrl
  WebsocketApiUrl:
    Description: "The URL for the Websocket API endpoint"
    Value: 
      Fn::GetAtt: 
      - WebsocketApi
      - Outputs.WebsocketApiUrl    
  ConsoleUrl:
    Description: The URL for the FormKiQ Console
    Value: 
      Fn::GetAtt: 
      - CoreConsole
      - Outputs.ConsoleUrl
  ConsoleS3Bucket:
    Description: The Console S3 Bucket
    Value: 
      Fn::GetAtt: 
      - CoreConsole
      - Outputs.ConsoleBucket
  CognitoUserPoolId:
    Description: "The Cognito User Pool Id"
    Value: 
      Fn::GetAtt: 
      - Cognito
      - Outputs.CognitoUserPoolId
  CognitoUserPoolArn:
    Description: "The Cognito User Pool Arn"
    Value: 
      Fn::GetAtt: 
      - Cognito
      - Outputs.CognitoUserPoolArn
  CognitoClientId:
    Description: "The Cognito Client Id"
    Value: 
      Fn::GetAtt: 
      - Cognito
      - Outputs.CognitoUserPoolClientId
  FormKiQVersion:
    Description: "The FormKiQ Version"
    Value: #@ data.values.version or assert.fail("missing version")
  SnsDocumentEventArn:
    Description: SNS Topic for Document Events
    Value: 
      Fn::GetAtt: 
      - CoreStorage
      - Outputs.SnsDocumentEventArn
  CognitoApiEndpoint:
    Description: The Cognito Login API endpoint
    Value: 
      Fn::GetAtt: 
      - Cognito
      - Outputs.ApiEndpoint
  DocumentsS3Buckets:
    Description: Documents Bucket.
    Value: 
      Fn::GetAtt: 
      - CoreStorage
      - Outputs.DocumentsS3Buckets
  DocumentsStageS3Bucket:
    Description: Documents Staging Bucket.
    Value: 
      Fn::GetAtt: 
      - CoreStorage
      - Outputs.DocumentsStageS3Bucket