#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: #@ "FormKiQ Core " + data.values.version or assert.fail("missing version")
        
Parameters:

  ConsoleWafACLId:
    Type: String
    Default: ""
    Description: (Optional) ARN of the Console WAF WebACL to associate with the CloudFront distribution. Leave empty to disable.

  AdminEmail:
    Type: String
    Description: Administrator Email (required)
    AllowedPattern: ".+"

  AppEnvironment:
    Type: String
    Description: Unique Application Environment Identifier, IE dev/staging/prod
    AllowedPattern: "[a-zA-Z0-9_.-/]+"
    Default: prod
  
  EnablePublicUrls:
    Description: >
      Whether to enable "/public" endpoints, defaults to false. Public endpoints allow external users to submit documents, such as through a web form. As with any publicly-available functionality, there is a risk of abuse if enabled.
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]
    
  PasswordMinimumLength:
    Type: Number
    Description: Set the Amazon Cognito password policies, minimum password length requirement for all users
    MinValue: "6"
    MaxValue: "99"
    Default: "8"
    
  PasswordRequireLowercase:
    Description: Set the Amazon Cognito password policies, to require one lowercase letter in all passwords.
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]
    
  PasswordRequireNumbers:
    Description: Set the Amazon Cognito password policies, to require one number in all passwords.
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]
    
  PasswordRequireSymbols:
    Description: Set the Amazon Cognito password policies, to require one symbol in all passwords.
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]
    
  PasswordRequireUppercase:
    Description: Set the Amazon Cognito password policies, to require one uppercase letter in all passwords.
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]

  VpcStackName:
    Type: String
    Description: >
      The name of the CloudFormation VPC stack that can be created after the initial FormKiQ install, using the add-on CloudFormation template for VPC https://docs.formkiq.com/docs/getting-started/quick-start#create-vpc.
      Some services such as Typesense, and OpenSearch require a VPC. Only required if you are using any of these services; otherwise, this can remain empty.
    Default: ""

  TypesenseApiKey:
    Type: String
    Description: >
      Optional: API Key to access the [Typesense](https://typesense.org) server. Typesense is used to provide full text search support for document metadata. The API Key can be any random string of characters. To enable Typesense, the `VpcStackName` also needs to be set.
    Default: ""

  TypesenseMemory:
    Type: String
    Description: The amount of memory used by Typesense (GB). (Suggested to be 2-3 times the size of your data)
    Default: "1024"
    AllowedValues: ["1024", "2048", "3072", "4096", "5120", "6144", "7168", "8192", "16384", "32768"]
    
  CapacityProvider:
    Description: AWS Fargate capacity provider to use, either the FARGATE or FARGATE_SPOT 
    Default: "FARGATE_SPOT"
    Type: String
    AllowedValues: ["FARGATE_SPOT", "FARGATE"]

  LogRetentionInDays:
    Type: Number
    Description: The number of days to retain the log events 
    Default: 90
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1096
      - 1827
      - 2192
      - 2557
      - 2922
      - 3288
      - 3653

  LogFormat:
    Description: >
      The format in which the application and system logs are stored.
    Type: String
    AllowedValues: ["Text", "JSON"]
    Default: "Text"

  LogLevelApplication:
    Type: String
    Description: >
      The level of logging for the FormKiQ Application logs. Only used when LogFormat is JSON
    Default: "INFO"
    AllowedValues: ["TRACE", "DEBUG", "INFO", "ERROR"]

  LogLevelSystem:
    Type: String
    Description: >
      The level of logging for the AWS Platform System logs. Only used when LogFormat is JSON
    Default: "INFO"
    AllowedValues: ["DEBUG", "INFO", "WARN"]
      
Conditions:

  HasTypesenseApiKey:
    Fn::Not:
      - Fn::Equals: 
        - Ref: TypesenseApiKey
        - ''

  IsGovCloud:
    Fn::Or:
      - Fn::Equals:
          - Ref: AWS::Region
          - us-gov-west-1
      - Fn::Equals:
          - Ref: AWS::Region
          - us-gov-east-1

Resources:

  EditionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "FormKiQ Edition"
      Name:
        Fn::Sub: "/formkiq/${AppEnvironment}/edition"
      Type: String
      Value:
        Fn::GetAtt:
          - Config
          - Outputs.FormKiQType
      Tags:
        Application: "FormKiQ"
        AppEnvironment:
          Fn::Sub: "${AppEnvironment}"

  VersionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "FormKiQ Version"
      Name:
        Fn::Sub: "/formkiq/${AppEnvironment}/version"
      Type: String
      Value:
        Fn::GetAtt:
          - Config
          - Outputs.FormKiQVersion
      Tags:
        Application: "FormKiQ"
        AppEnvironment:
          Fn::Sub: "${AppEnvironment}"

  Config:
    Type: AWS::Serverless::Application
    Properties:
      Location: config.yaml
      Parameters:
        FormKiQType: "core"
        FormKiQVersion: #@ data.values.version or assert.fail("missing version")

  EventMessages:
    Type: AWS::Serverless::Application
    Properties:
      Location: event-message.yaml
      Parameters:
        AppEnvironment:
          Ref: AppEnvironment

  CoreStorage:
    Type: AWS::Serverless::Application
    DependsOn:
      - EventMessages
    Properties:
      Location: storage/template.yaml
      Parameters:
        TypesenseApiKey:
          Ref: TypesenseApiKey
        LogRetentionInDays:
          Ref: LogRetentionInDays
        LogFormat:
          Ref: LogFormat
        LogLevelApplication:
          Ref: LogLevelApplication
        LogLevelSystem:
          Ref: LogLevelSystem
        VpcStackName:
          Ref: VpcStackName
        AppEnvironment: 
          Ref: AppEnvironment
        FormKiQType:
          Fn::GetAtt:
            - Config
            - Outputs.FormKiQType
        DocumentEventsBus:
          Fn::GetAtt:
            - EventMessages
            - Outputs.DocumentEventsBus
      Tags:
        Application: "FormKiQ"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"

  CoreConsole:
    Type: AWS::Serverless::Application
    Properties:
      Location: console/template.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
        FormKiQType:
          Fn::GetAtt:
            - Config
            - Outputs.FormKiQType
        AdminEmail: 
          Ref: AdminEmail
        WAFWebACLId:
          Ref: ConsoleWafACLId
        IsGovCloud:
          Fn::If:
          - IsGovCloud
          - "true"
          - "false"

  CoreConsoleInstall:
    Type: AWS::Serverless::Application
    DependsOn:
      - CoreApi
      - Cognito
    Properties:
      Location: console/template-install.yaml
      Parameters:
        LogFormat:
          Ref: LogFormat
        LogLevelApplication:
          Ref: LogLevelApplication
        LogLevelSystem:
          Ref: LogLevelSystem
        IsGovCloud:
          Fn::If:
          - IsGovCloud
          - "true"
          - "false"
        AppEnvironment: 
          Ref: AppEnvironment
        ConsoleVersion: 
          Fn::GetAtt: 
          - CoreConsole
          - Outputs.ConsoleVersion
        ConsoleBucket: 
          Fn::GetAtt: 
          - CoreConsole
          - Outputs.ConsoleBucket
        ApiUrl: 
          Fn::GetAtt: 
          - CoreApi
          - Outputs.DocumentsHttpApiUrl
        IamApiUrl:
          Fn::GetAtt:
            - CoreApi
            - Outputs.DocumentsIamApiUrl
        KeyApiUrl:
          Fn::GetAtt:
            - CoreApi
            - Outputs.DocumentsKeyApiUrl
        WebsocketApiUrl: 
          Fn::GetAtt: 
          - WebsocketApi
          - Outputs.WebsocketApiUrl
        AuthApiUrl: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.ApiEndpoint
        AllowAdminCreateUserOnly: "true"
        CognitoHostedUi:
          Fn::GetAtt:
          - Cognito
          - Outputs.CognitoHostedUi
        CognitoUserPoolId:
          Fn::GetAtt:
          - Cognito
          - Outputs.CognitoUserPoolId
        CognitoUserPoolClientId:
          Fn::GetAtt:
          - Cognito
          - Outputs.CognitoUserPoolClientId
        CognitoConfigBucket:
          Fn::GetAtt:
          - Cognito
          - Outputs.CognitoConfigBucket
        Domain:
          Fn::GetAtt:
          - Cognito
          - Outputs.Domain
        HostedZoneId:
          Fn::GetAtt:
          - CoreConsole
          - Outputs.HostedZoneId
        CloudFrontDistributionDomainName: 
          Fn::GetAtt:
          - CoreConsole
          - Outputs.CloudFrontDistributionDomainName

  Cognito:
    Type: AWS::Serverless::Application
    DependsOn:
      - CoreConsole
    Properties:
      Location: cognito/template.yaml
      Parameters:
        UserPoolName: 
          Fn::Sub: "${AWS::StackName}-${AppEnvironment}"
        AllowAdminCreateUserOnly: "true"
        PasswordMinimumLength: 
          Fn::Sub: "${PasswordMinimumLength}"
        PasswordRequireLowercase: 
          Fn::Sub: "${PasswordRequireLowercase}"
        PasswordRequireNumbers: 
          Fn::Sub: "${PasswordRequireNumbers}"
        PasswordRequireSymbols: 
          Fn::Sub: "${PasswordRequireSymbols}"
        PasswordRequireUppercase: 
          Fn::Sub: "${PasswordRequireUppercase}"
        Domain: 
          Fn::Sub: "${AppEnvironment}${AWS::AccountId}"
        LogRetentionInDays:
          Ref: LogRetentionInDays
        LogFormat:
          Ref: LogFormat
        LogLevelApplication:
          Ref: LogLevelApplication
        LogLevelSystem:
          Ref: LogLevelSystem
        RedirectUrl:
          Fn::GetAtt:
          - CoreConsole
          - Outputs.ConsoleUrl
        
  SsmProperties:
    Type: AWS::Serverless::Application
    DependsOn:
      - Cognito
    Properties:
      Location: ./ssm-template.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
        CognitoUserPool: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolId
        CognitoUserPoolArn: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolArn
        CognitoUserPoolClient: 
          Fn::GetAtt:
          - Cognito
          - Outputs.CognitoUserPoolClientId
        CognitoIdentityPool: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoIdentityPoolId
        Domain: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.Domain
        
  CoreApi:
    Type: AWS::Serverless::Application
    DependsOn:
      - Cognito
      - WebsocketApi
      - TypeSenseService
    Properties:
      Location: api/template.yaml
      Parameters:
        AppEnvironment:
          Ref: AppEnvironment
        LogRetentionInDays:
          Ref: LogRetentionInDays
        LogFormat:
          Ref: LogFormat
        LogLevelApplication:
          Ref: LogLevelApplication
        LogLevelSystem:
          Ref: LogLevelSystem
        EnablePublicUrls: 
          Ref: EnablePublicUrls
        PasswordMinimumLength: 
          Ref: PasswordMinimumLength
        PasswordRequireLowercase: 
          Ref: PasswordRequireLowercase
        PasswordRequireNumbers: 
          Ref: PasswordRequireNumbers
        PasswordRequireSymbols: 
          Ref: PasswordRequireSymbols
        PasswordRequireUppercase: 
          Ref: PasswordRequireUppercase
        CognitoUserPool: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolId
        CognitoUserPoolClient: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolClientId
        WebsocketSqsQueueUrl: 
          Fn::GetAtt: 
          - WebsocketApi
          - Outputs.SqsQueueUrl
        TypesenseApiKey: 
          Ref: TypesenseApiKey
        TypesenseApiEndpoint:
          Fn::GetAtt:
          - TypeSenseService
          - Outputs.TypesenseApiEndpoint
        VpcStackName:
          Ref: VpcStackName
        FormKiQType:
          Fn::GetAtt:
            - Config
            - Outputs.FormKiQType
        FormKiQVersion:
          Fn::GetAtt:
            - Config
            - Outputs.FormKiQVersion
      Tags:
        Application: "FormKiQ"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"

  CoreConsoleUsers:
    Type: AWS::Serverless::Application
    DependsOn:
      - CoreApi
      - SsmProperties
      - CoreConsoleInstall
    Properties:
      Location: console/template-users.yaml
      Parameters:
        IsGovCloud:
          Fn::If:
          - IsGovCloud
          - "true"
          - "false"
        AppEnvironment:
          Ref: AppEnvironment
        AdminEmail: 
          Ref: AdminEmail
        CognitoUserPool: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolId
        CognitoUserPoolArn: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolArn
        CognitoIdentityPool: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoIdentityPoolId
        CognitoUserPoolClient: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolClientId
          
  WebsocketApi:
    Type: AWS::Serverless::Application
    DependsOn:
      - Cognito
      - CoreStorage
    Properties:
      Location: websocket-api/template.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
        FormKiQType:
          Fn::GetAtt:
            - Config
            - Outputs.FormKiQType
        LogRetentionInDays:
          Ref: LogRetentionInDays
        LogFormat:
          Ref: LogFormat
        LogLevelApplication:
          Ref: LogLevelApplication
        LogLevelSystem:
          Ref: LogLevelSystem
        CognitoUserPoolId: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolId
        CognitoUserPoolClientId: 
          Fn::GetAtt: 
          - Cognito
          - Outputs.CognitoUserPoolClientId

  EcsCluster:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./ecs-cluster.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
        TypesenseApiKey:
          Ref: TypesenseApiKey
        VpcStackName:
          Ref: VpcStackName
        CapacityProvider:
          Ref: CapacityProvider
            
  TypeSenseService:
    Type: AWS::Serverless::Application
    DependsOn:
      - EcsCluster
      - CoreStorage
    Properties:
      Location: typesense/template.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
        FormKiQType:
          Fn::GetAtt:
            - Config
            - Outputs.FormKiQType
        TypesenseApiKey:
          Ref: TypesenseApiKey
        VpcStackName:
          Ref: VpcStackName
        ECSCluster: 
          Fn::GetAtt: 
          - EcsCluster
          - Outputs.ECSCluster
        TypesenseMemory:
          Ref: TypesenseMemory
        LogRetentionInDays:
          Ref: LogRetentionInDays
        LogFormat:
          Ref: LogFormat
        LogLevelApplication:
          Ref: LogLevelApplication
        LogLevelSystem:
          Ref: LogLevelSystem

  TypesenseApiKeyParameter:
    Type: AWS::SSM::Parameter
    Condition: HasTypesenseApiKey
    Properties:
      Description: "Typesense API Key"
      Name: 
        Fn::Sub: "/formkiq/${AppEnvironment}/typesense/ApiKey"
      Type: String
      Value:      
        Ref: TypesenseApiKey
      Tags:
        Application: 
          Fn::Sub: "FormKiQ"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
          
  CognitoApiIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Cognito API ID"
      Name: 
        Fn::Sub: "/formkiq/${AppEnvironment}/api/CognitoApiId"
      Type: String
      Value:
        Fn::GetAtt: 
        - Cognito
        - Outputs.HttpApi
      Tags:
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
          
  Monitoring:
    Type: AWS::Serverless::Application
    DependsOn:
      - TypeSenseService
      - CoreStorage
      - CoreApi
      - Cognito
    Properties:
      Location: ./monitoring.yaml
      Parameters:
        AppEnvironment: 
          Ref: AppEnvironment
                    
Outputs:
  AppEnvironment:
    Description: Unique Application Environment Identifier, IE dev/staging/prod
    Value: 
      Ref: AppEnvironment
  IamApiUrl:
    Description: "The URL for the API endpoint that uses IAM authorization"
    Value: 
      Fn::GetAtt: 
      - CoreApi
      - Outputs.DocumentsIamApiUrl
  KeyApiUrl:
    Description: "The URL for the API endpoint that uses API Key authorization"
    Value: 
      Fn::GetAtt: 
      - CoreApi
      - Outputs.DocumentsKeyApiUrl
  HttpApiUrl:
    Description: "The URL for the API endpoint that uses Cognito authorization"
    Value: 
      Fn::GetAtt: 
      - CoreApi
      - Outputs.DocumentsHttpApiUrl
  WebsocketApiUrl:
    Description: "The URL for the Websocket API endpoint"
    Value: 
      Fn::GetAtt: 
      - WebsocketApi
      - Outputs.WebsocketApiUrl    
  ConsoleUrl:
    Description: The URL for the FormKiQ Console
    Value: 
      Fn::GetAtt: 
      - CoreConsole
      - Outputs.ConsoleUrl
  ConsoleS3Bucket:
    Description: The Console S3 Bucket
    Value: 
      Fn::GetAtt: 
      - CoreConsole
      - Outputs.ConsoleBucket
  CognitoUserPoolId:
    Description: "The Cognito User Pool Id"
    Value: 
      Fn::GetAtt: 
      - Cognito
      - Outputs.CognitoUserPoolId
  CognitoUserPoolArn:
    Description: "The Cognito User Pool Arn"
    Value: 
      Fn::GetAtt: 
      - Cognito
      - Outputs.CognitoUserPoolArn
  CognitoClientId:
    Description: "The Cognito Client Id"
    Value: 
      Fn::GetAtt: 
      - Cognito
      - Outputs.CognitoUserPoolClientId
  FormKiQVersion:
    Description: "The FormKiQ Version"
    Value: #@ data.values.version or assert.fail("missing version")
  SnsDocumentEventArn:
    Description: SNS Topic for Document Events
    Value: 
      Fn::GetAtt: 
      - CoreStorage
      - Outputs.SnsDocumentEventArn
  DocumentsTableName:
    Description: Document DynamoDb Table Name
    Value: 
      Fn::GetAtt: 
      - CoreStorage
      - Outputs.DocumentsTableName
  DocumentsTableArn:
    Description: Document DynamoDb Table Arn
    Value:
      Fn::GetAtt:
        - CoreStorage
        - Outputs.DocumentsTableArn
  CognitoApiEndpoint:
    Description: The Cognito Login API endpoint
    Value: 
      Fn::GetAtt: 
      - Cognito
      - Outputs.ApiEndpoint
  DocumentsS3Buckets:
    Description: Documents Bucket.
    Value: 
      Fn::GetAtt: 
      - CoreStorage
      - Outputs.DocumentsS3Buckets
  DocumentsStageS3Bucket:
    Description: Documents Staging Bucket.
    Value: 
      Fn::GetAtt: 
      - CoreStorage
      - Outputs.DocumentsStageS3Bucket
      
  TypesenseApiEndpoint:
    Description: Typesense API endpoint
    Value:
      Fn::GetAtt:
      - TypeSenseService
      - Outputs.TypesenseApiEndpoint