name: OWASP Dependency Check

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 6 * * 1'

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Project
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: '${{ github.repository }}'
          path: '.'
          format: 'HTML,JSON,XML'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --scan ./pom.xml
            --scan ./build.gradle
            --scan ./build.gradle.kts
            --enableRetired

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-report
          path: reports
