#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FormKiQ Core - Lucene
    
Parameters:
    
  AppEnvironment:
    Type: String
    Description: The Application Environment
    AllowedPattern: ".+"

  LambdaMemory:
    Type: Number
    Description: The amount of memory used by lambda function (MB)
    Default: 1024
    MinValue: 128
    MaxValue: 3008
  
  LambdaTimeout:
    Type: String
    Description: The maximum amount of seconds lambda function will run for (seconds)
    Default: 60

  FormKiQType:
    Description: The type of FormKiQ installation
    Default: "core"
    Type: String
    AllowedValues: ["core", "enterprise"]

  VpcStackName:
    Type: String
    Description: The name of the FormKiQ VPC Stack Name

Conditions:
  HasVpcStackName:
    Fn::Not:
      - Fn::Equals: 
        - Ref: VpcStackName
        - ''
        
Resources:
      
  LuceneProcessor:
    Type: AWS::Serverless::Function
    Condition: HasVpcStackName
    DependsOn:
    - LuceneLambdaRolePolicy
    Properties:
      Handler: com.formkiq.module.lambda.lucene.LuceneProcessor
      Description: Lambda function to add DynamoDB records to Lucene
      Runtime: provided
      Timeout: 
        Fn::Sub: "${LambdaTimeout}"
      MemorySize: 
        Fn::Sub: "${LambdaMemory}"
      CodeUri: ./formkiq-module-lambda-lucene-graalvm.zip
      AutoPublishCodeSha256: #@ data.values.hash or assert.fail("missing version")
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          APP_ENVIRONMENT: 
            Fn::Sub: "${AppEnvironment}"
          DEBUG: false  
          FormKiQType:
            Ref: FormKiQType
          LUCENE_BASE_PATH: "/lucene"
      Role: 
        Fn::GetAtt:
        - LuceneLambdaRole
        - Arn
      Tags:
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        Application: 
          Fn::Sub: "FormKiQ ${FormKiQType}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"
      VpcConfig:
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue:
                Fn::Sub: '${VpcStackName}-PrivateSubnets'
        SecurityGroupIds:
          Fn::Split:
          - ","
          - Fn::ImportValue:
              Fn::Sub: '${VpcStackName}-HttpsSecurityGroup'
                
  LuceneProcessorParameter:
    Type: AWS::SSM::Parameter
    Condition: HasVpcStackName
    Properties:
      Description: "Lambda for processing records for Lucene"
      Name: 
        Fn::Sub: "/formkiq/${AppEnvironment}/lambda/LuceneProcessor"
      Type: String
      Value: 
        Ref: LuceneProcessor
      Tags:
        Application: 
          Fn::Sub: "FormKiQ ${FormKiQType}"
        AppEnvironment: 
          Fn::Sub: "${AppEnvironment}"
        StackName: 
          Fn::Sub: "${AWS::StackName}"

  LuceneLambdaRole:
    Type: AWS::IAM::Role
    Condition: HasVpcStackName
    Properties:
      Tags:
        - Key: "Application"
          Value: 
            Fn::Sub: "FormKiQ ${FormKiQType}"        
        - Key: "AppEnvironment"
          Value: 
            Fn::Sub: "${AppEnvironment}"
        - Key: "StackName"
          Value: 
            Fn::Sub: "${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      
  LuceneLambdaRolePolicy: 
    Type: "AWS::IAM::Policy"
    Condition: HasVpcStackName
    Properties: 
      PolicyName: Lucene-lambdarole
      Roles: 
        - 
          Ref: "LuceneLambdaRole"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
          - Effect: Allow
            Action:
            - dynamodb:DescribeStream
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:ListStreams
            Resource: 
            - Fn::Sub: "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/{{resolve:ssm:/formkiq/${AppEnvironment}/dynamodb/DocumentsTableName}}/stream/*"

  LuceneTableStream:
    Type: AWS::Lambda::EventSourceMapping
    Condition: HasVpcStackName
    Properties:
      Enabled: True
      EventSourceArn:
        Fn::Sub: "{{resolve:ssm:/formkiq/${AppEnvironment}/dynamodb/DocumentsStreamArn}}"
      FunctionName:
        Fn::GetAtt:
        - LuceneProcessor
        - Arn      
      StartingPosition: LATEST
      
  LuceneEfs:
    Type: 'AWS::EFS::FileSystem'
    Condition: HasVpcStackName
    Properties:
      BackupPolicy:
        Status: ENABLED
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: 
            Fn::Sub: "FormKiQ Lucene ${AppEnvironment}"
        - Key: "Application"
          Value: 
            Fn::Sub: "FormKiQ ${FormKiQType}"        
        - Key: "AppEnvironment"
          Value: 
            Fn::Sub: "${AppEnvironment}"
        - Key: "StackName"
          Value: 
            Fn::Sub: "${AWS::StackName}"

  MountTargetResource1:
    Type: AWS::EFS::MountTarget
    Condition: HasVpcStackName
    Properties:
      FileSystemId: 
        Ref: LuceneEfs
      SubnetId: 
        Fn::ImportValue:
          Fn::Sub: '${VpcStackName}-PrivateSubnet1'
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: '${VpcStackName}-NfsSecurityGroup'

  MountTargetResource2:
    Type: AWS::EFS::MountTarget
    Condition: HasVpcStackName
    Properties:
      FileSystemId: 
        Ref: LuceneEfs
      SubnetId: 
        Fn::ImportValue:
          Fn::Sub: '${VpcStackName}-PrivateSubnet2'
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: '${VpcStackName}-NfsSecurityGroup'
          
  MountTargetResource3:
    Type: AWS::EFS::MountTarget
    Condition: HasVpcStackName
    Properties:
      FileSystemId: 
        Ref: LuceneEfs
      SubnetId: 
        Fn::ImportValue:
          Fn::Sub: '${VpcStackName}-PrivateSubnet3'
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: '${VpcStackName}-NfsSecurityGroup'
           
  LuceneEfsAccessPoint:
    Type: 'AWS::EFS::AccessPoint'
    Condition: HasVpcStackName
    Properties:
      FileSystemId: 
        Ref: LuceneEfs
      PosixUser:
        Uid: "1000"
        Gid: "1000"
      RootDirectory:
        CreationInfo:
          OwnerGid: "1000"
          OwnerUid: "1000"
          Permissions: "0777"
        Path: "/lucene"